const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})}),p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('node:url').pathToFileURL(require('node:path').join(__dirname,'../index.html')).href);await p.waitForFunction(()=>forma.renderer);
await p.evaluate(()=>{forma.setState({...Volumetry.defaults,n:1,crown:0,floors:8});const f=forma.getModel().floorCatalog.find(b=>b.key==='6:0'),parts=FloorDesign.split(f.polys,[0,-100],[0,100]);forma.setState({floorFocus:f.key,floorEdits:{[f.key]:{polys:f.polys,sectors:parts.map((polys,i)=>({id:'s'+i,name:'Setor '+i,use:'apartment',polys}))}}});});
const initial=await p.evaluate(()=>forma.getModel().area);await p.locator('#edit-floor').click();await p.locator('#floor-sectors').click();const v=await p.locator('#floor-plan [data-vertex]').evaluateAll(es=>es.map(e=>({key:e.getAttribute('data-vertex'),x:+e.getAttribute('cx'),y:+e.getAttribute('cy')})).filter(e=>Math.abs(e.x-360)<1).sort((a,b)=>a.y-b.y)[0]);assert.ok(v);const handle=p.locator(`#floor-plan [data-vertex="${v.key}"]`);await handle.scrollIntoViewIfNeeded();const bb=await handle.boundingBox();await p.mouse.move(bb.x+bb.width/2,bb.y+bb.height/2);await p.mouse.down();await p.mouse.move(bb.x+bb.width/2+24,bb.y+bb.height/2,{steps:4});await p.mouse.up();assert.ok(await p.locator('#floor-apply').isEnabled());await p.locator('#floor-apply').click();const audit=await p.evaluate(()=>{const f=forma.getModel().floorCatalog.find(b=>b.key==='6:0');return{area:forma.getModel().area,sectors:f.sectors.map(s=>LotGeometry.area(s.polys)),audit:FloorDesign.sectorAudit(f.polys,f.sectors)};});assert.ok(Math.abs(audit.area-initial)<1e-5);assert.notEqual(audit.sectors[0],audit.sectors[1]);assert.deepEqual(audit.audit.errors,[]);assert.ok(audit.audit.unassigned<1e-5);
// Shrinking a lower edited floor must flag unsupported automatic floors above it.
await p.evaluate(()=>{const f=forma.getModel().floorCatalog.find(b=>b.key==='5:0');forma.setState({floorEdits:{...forma.getState().floorEdits,'5:0':{polys:LotGeometry.rect({x:-3,z:-3,w:6,d:6}),sectors:[]}}});});assert.ok(await p.evaluate(()=>forma.getModel().floorIssues.some(i=>i.key==='6:0'&&i.message.includes('Balanço'))));
await p.evaluate(()=>forma.setState({...Volumetry.defaults,n:1,crown:0,floors:12,ground:3,mode:'open',baseFloors:0,fill:100,depth:100,floorEdits:{},floorFocus:'4:0'}));await p.locator('#edit-floor').click();await p.getByText('Copiar para outros pavimentos',{exact:true}).click();await p.locator('#floor-copy-start').fill('6');await p.locator('#floor-copy-end').fill('8');await p.locator('#floor-copy-preview').click();assert.ok(await p.locator('#floor-copy-apply').isDisabled());assert.match(await p.locator('#floor-copy-report').innerText(),/fora da camisa/);await p.getByRole('button',{name:'Fechar pavimento sem aplicar'}).click();
await p.evaluate(()=>{forma.setState({floorFocus:'6:0'});const f=forma.getModel().floorCatalog.find(b=>b.key==='6:0');forma.setState({floorEdits:{'6:0':{polys:f.polys,sectors:[]}}});});await p.locator('#save-option').click();await p.evaluate(()=>forma.setState({floorEdits:{}}));await p.locator('.option-card').first().getByRole('button',{name:'Usar esta alternativa'}).click();assert.ok(await p.evaluate(()=>forma.getState().floorEdits['6:0']));
await p.locator('#theme').click();await p.locator('#edit-floor').click();await p.screenshot({path:__dirname+'/forma-v06-dark.png',fullPage:true});await p.getByRole('button',{name:'Fechar pavimento sem aplicar'}).click();assert.equal(await p.evaluate(()=>forma.renderer.error),0);assert.deepEqual(errors,[]);await b.close();fs.writeFileSync(__dirname+'/validacao-edicoes-v06.json',JSON.stringify({checks:5,errors,tests:['Shared boundary drag preserves partition','Support conflict on higher floor','Copy rejects upper setback violation','Alternative recovery includes edits','Dark editor/render']},null,2));console.log('PASS five editing edge cases');})().catch(e=>{console.error(e);process.exit(1);});
