const assert=require('node:assert/strict'),fs=require('node:fs'),V=require('../src/volumetria-v3-core.js'),G=require('../src/volumetria-v4-polygon.js'),F=require('../src/volumetria-v5-floors.js'),PC=F.PC;G.install(V);F.install(V);require('../src/volumetria-v4-crown.js').install(V,G,require('../src/polygon-clipping-0.15.7.js'));let checks=0,scenarios=0;function test(name,fn){fn();checks++;console.log('PASS',name);}const base=()=>V.normalize({...V.defaults,n:1,floors:8,crown:0}),sector=(id,polys,use='apartment')=>({id,name:id,use,polys});
test('Splits conserve area for rectangle, trapezoid and concave rings',()=>{for(const r of [[[0,0],[40,0],[40,60],[0,60]],[[0,0],[40,0],[30,60],[10,60]],[[0,0],[60,0],[60,20],[20,20],[20,60],[0,60]]])for(let angle=0;angle<180;angle+=15){const ps=[[r.concat([r[0]])]],a=[15,15],b=[15+100*Math.cos(angle*Math.PI/180),15+100*Math.sin(angle*Math.PI/180)],parts=F.split(ps,a,b);assert.ok(Math.abs(parts.reduce((v,p)=>v+G.area(p),0)-G.area(ps))<1e-5);assert.ok(G.area(PC.intersection(...parts))<1e-5);scenarios++;}});
test('Reject zero-length and exterior splitting lines',()=>{const ps=G.rect({x:0,z:0,w:20,d:20});assert.throws(()=>F.split(ps,[2,2],[2,2]));assert.throws(()=>F.split(ps,[-2,-2],[-2,20]));});
test('Sector overlaps/outside are detected; deletion leaves unassigned area',()=>{const ps=G.rect({x:0,z:0,w:20,d:20}),a=G.rect({x:0,z:0,w:12,d:20}),b=G.rect({x:10,z:0,w:12,d:20});assert.ok(F.sectorAudit(ps,[sector('a',a),sector('b',b)]).errors.length===2);assert.equal(F.sectorAudit(ps,[sector('a',a)]).unassigned,160);});
test('Custom floors persist across height and lot changes and are not clipped',()=>{const s=base(),m=V.calculate(s),p=m.floorCatalog.find(b=>b.key==='6:0'),ps=G.rect({x:-21,z:-20,w:40,d:40});s.floorEdits[p.key]={polys:ps,sectors:[]};const out=V.calculate({...s,ground:6,storey:5});assert.deepEqual(out.floorCatalog.find(b=>b.key===p.key).polys,ps);assert.ok(out.floorIssues.some(i=>i.key===p.key));assert.deepEqual(V.normalize(s).floorEdits,s.floorEdits);const reduced=V.calculate({...s,floors:2});assert.ok(reduced.p.floorEdits[p.key]);assert.ok(reduced.floorIssues.some(i=>i.message.includes('sem pavimento')));});
test('Union of projections handles a shifted custom floor',()=>{const s=base(),m=V.calculate(s),floor=m.floorCatalog.find(b=>b.key==='6:0'),ps=clone(floor.polys);function clone(o){return JSON.parse(JSON.stringify(o));}for(const ring of ps.flat())for(const p of ring)p[0]+=15;s.floorEdits[floor.key]={polys:ps,sectors:[]};const n=V.calculate(s),union=PC.union(...n.boxes.filter(b=>b.type!=='crown').map(b=>b.polys||G.rect(b)));assert.ok(Math.abs(n.projection-G.area(union))<1e-5);assert.ok(n.floorIssues.some(i=>i.message.includes('Balanço')));});
test('Apartments count per sector and floor; setorização does not change envelope or outline',()=>{const s=base(),m=V.calculate(s),floor=m.floorCatalog.find(b=>b.key==='6:0'),parts=F.split(floor.polys,[0,-100],[0,100]);s.floorEdits[floor.key]={polys:floor.polys,sectors:parts.map((p,i)=>sector('a'+i,p))};const n=V.calculate(s);assert.equal(n.program.units,2);assert.ok(Math.abs(n.area-m.area)<1e-5);assert.deepEqual(n.envelope,m.envelope);assert.deepEqual(n.floorCatalog.find(b=>b.key===floor.key).polys,floor.polys);});
const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})}),page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(require('node:url').pathToFileURL(require('node:path').join(__dirname,'../index.html')).href);await page.waitForFunction(()=>forma.renderer);await page.evaluate(s=>forma.setState(s),base());await page.locator('#floor-picker').selectOption('6:0');await page.locator('#edit-floor').click();await page.locator('#floor-split').click();const bb=await page.locator('#floor-plan').boundingBox();for(const y of [.12,.88])await page.mouse.click(bb.x+bb.width*.5,bb.y+bb.height*y);assert.equal(await page.locator('#sector-select option').count(),2);await page.locator('#sector-use').selectOption('apartment');await page.locator('#sector-name').fill('Apto 601');await page.locator('#sector-name').dispatchEvent('change');await page.locator('#floor-apply').click();assert.equal(await page.evaluate(()=>forma.getModel().program.units),1);checks++;
await page.locator('#isolate-floor').check();await page.screenshot({path:__dirname+'/forma-v06-sectors-3d.png',fullPage:true});assert.equal(await page.evaluate(()=>forma.renderer.error),0);checks++;
await page.locator('#edit-floor').click();await page.getByText('Copiar para outros pavimentos',{exact:true}).click();await page.locator('#floor-copy-start').fill('7');await page.locator('#floor-copy-end').fill('8');await page.locator('#floor-copy-preview').click();assert.ok(await page.locator('#floor-copy-apply').isEnabled());await page.locator('#floor-copy-apply').click();assert.equal(await page.evaluate(()=>forma.getModel().program.units),3);checks++;
await page.reload();await page.waitForFunction(()=>forma.renderer);assert.equal(await page.evaluate(()=>forma.getModel().program.units),3);checks++;
await page.locator('#edit-floor').click();await page.locator('#floor-sectors').click();await page.locator('#sector-merge').click();assert.equal(await page.locator('#sector-select option').count(),1);await page.locator('#floor-draft-undo').click();assert.equal(await page.locator('#sector-select option').count(),2);await page.getByRole('button',{name:'Fechar pavimento sem aplicar'}).click();checks++;
await page.locator('#edit-floor').click();await page.locator('#floor-outline').click();await page.getByText('Editar coordenadas do contorno',{exact:true}).click();await page.getByRole('spinbutton',{name:'Vértice 1, X',exact:true}).fill('-100');await page.getByRole('spinbutton',{name:'Vértice 1, X',exact:true}).dispatchEvent('change');await page.locator('#floor-clear-sectors').click();await page.locator('#floor-apply').click();assert.ok(await page.evaluate(()=>forma.getModel().floorIssues.some(i=>i.key==='6:0')));assert.equal(await page.evaluate(()=>forma.getState().floorEdits['6:0'].polys[0][0][0][0]),-100);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>forma.getModel().program.units),3);checks++;
await page.locator('#tab-rules').click();const pending=page.waitForEvent('download');await page.locator('#export-study').click();await(await pending).saveAs(__dirname+'/Forma-v06-teste.json');const data=JSON.parse(fs.readFileSync(__dirname+'/Forma-v06-teste.json'));assert.equal(data.version,'06');assert.equal(data.results.program.units,3);assert.equal(Object.keys(data.state.floorEdits).length,3);checks++;
await page.locator('#edit-floor').click();await page.screenshot({path:__dirname+'/forma-v06-editor.png',fullPage:true});for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('#floor-editor').evaluate(e=>e.scrollWidth<=e.clientWidth));if(width===390)await page.screenshot({path:__dirname+'/forma-v06-mobile.png',fullPage:true});checks++;}await page.getByRole('button',{name:'Fechar pavimento sem aplicar'}).click();
// Ray picking must resolve a real visible floor for at least one sampled screen point.
const hit=await page.evaluate(()=>{const c=document.getElementById('scene');for(let y=240;y<c.clientHeight-80;y+=15)for(let x=80;x<c.clientWidth-80;x+=15){const k=forma.renderer.pickFloor(x,y);if(k)return{k,x,y};}return null;});assert.ok(hit);assert.ok(await page.evaluate(k=>forma.getModel().floorCatalog.some(b=>b.key===k),hit.k));checks++;
await page.locator('#pick-floor').click();await page.locator('#scene').scrollIntoViewIfNeeded();const scene=await page.locator('#scene').boundingBox();await page.mouse.click(scene.x+hit.x,scene.y+hit.y);assert.ok(await page.locator('#floor-editor').isVisible());await page.getByRole('button',{name:'Fechar pavimento sem aplicar'}).click();checks++;
assert.deepEqual(errors,[]);await browser.close();fs.writeFileSync(__dirname+'/validacao-volumetria-v06.json',JSON.stringify({checks,splitScenarios:scenarios,errors,browser:'Edge'},null,2));console.log('COMPLETE',checks,'checks',scenarios,'split scenarios');})().catch(e=>{console.error(e);process.exit(1);});

