from pathlib import Path
p=Path(__file__).parent
def read(n): return (p/n).read_text(encoding='utf-8-sig')
def write(n,s): (p/n).write_text(s,encoding='utf-8')
r=read('volumetria-v3-renderer.js')
r=r.replace('function box(b,c){','''function polygonSurface(polys,y,c){for(const poly of polys){const flat=earcut.flatten(poly),indices=earcut(flat.vertices,flat.holes,2);for(const i of indices)vertices.push(flat.vertices[i*2],y,flat.vertices[i*2+1],0,1,0,...c);}}
function polygonBox(b,c){if(!b.openTop)polygonSurface(b.polys,b.y+b.h,c);for(const poly of b.polys)for(const ring of poly)for(let i=1;i<ring.length;i++){const a=ring[i-1],q=ring[i],dx=q[0]-a[0],dz=q[1]-a[1],len=Math.hypot(dx,dz)||1;quad([[a[0],b.y,a[1]],[q[0],b.y,q[1]],[q[0],b.y+b.h,q[1]],[a[0],b.y+b.h,a[1]]],c,[dz/len,0,-dx/len]);}}
function box(b,c){if(b.polys){polygonBox(b,c);return;}''')
r=r.replace("for(const [key,r]of Object.entries(p.roads)){if(!r.enabled)continue;", "for(const [key,r]of Object.entries(p.roads)){if(p.lotMode==='polygon'||!r.enabled)continue;")
r=r.replace("if(hr.enabled&&vr.enabled)","if(p.lotMode!=='polygon'&&hr.enabled&&vr.enabled)")
r=r.replace("plane(-p.w/2,-p.d/2,p.w,p.d,-.08,rgb(colors.lot));", """if(model.lotRing){const ring=model.lotRing,sign=LotGeometry.signed(ring)>0?1:-1;ring.forEach((a,i)=>{const e=p.edges[i];if(!e.frontage)return;const b=ring[(i+1)%ring.length],len=Math.hypot(b[0]-a[0],b[1]-a[1]),nx=(b[1]-a[1])/len*sign,nz=-(b[0]-a[0])/len*sign;const strip=(lo,hi,y,c)=>quad([[a[0]+nx*lo,y,a[1]+nz*lo],[b[0]+nx*lo,y,b[1]+nz*lo],[b[0]+nx*hi,y,b[1]+nz*hi],[a[0]+nx*hi,y,a[1]+nz*hi]],rgb(c));strip(0,e.width,-.12,colors.road);strip(0,Math.min(2,e.width/4),-.11,colors.walk);strip(e.width-Math.min(2,e.width/4),e.width,-.11,colors.walk);});polygonSurface([[ring.concat([ring[0]])]],-.08,rgb(colors.lot));}else if(p.lotMode!=='polygon')plane(-p.w/2,-p.d/2,p.w,p.d,-.08,rgb(colors.lot));""")
r=r.replace("for(let j=8;j>=1;j--)","for(let j=(p.lotMode==='polygon'?0:8);j>=1;j--)")
r=r.replace("{box(b,rgb(b.type!=='crown'", "{box({...b,openTop:!!b.polys&&b.type!=='crown'},rgb(b.type!=='crown'")
# The slab owns the single top face; duplicate coplanar triangles cause z-fighting.
r=r.replace("plane(b.x,b.z,b.w,b.d,b.y+b.h+.001,rgb(b.type", "if(!b.polys)plane(b.x,b.z,b.w,b.d,b.y+b.h+.001,rgb(b.type")
r=r.replace("function wire(b){", """function wire(b){if(b.polys){for(const poly of b.polys)for(const ring of poly)for(let i=1;i<ring.length;i++){const a=ring[i-1],q=ring[i];for(const y of [b.y,b.y+b.h])vertices.push(a[0],y,a[1],0,0,0,...c,q[0],y,q[1],0,0,0,...c);vertices.push(a[0],b.y,a[1],0,0,0,...c,a[0],b.y+b.h,a[1],0,0,0,...c);}return;}""")
r=r.replace("label(p.w+' m · frente'", "if(p.lotMode!=='polygon')label(p.w+' m · frente'").replace("if(W>500)label(p.d", "if(W>500&&p.lotMode!=='polygon')label(p.d")
r=r.replace("const padding=8,", "const padding=p.lotMode==='polygon'?Math.max(8,...p.edges.filter(e=>e.frontage).map(e=>e.width)):8,")
write('volumetria-v4-renderer.js',r)
a=read('volumetria-v3-app.js').replace("key='forma.volumetria.v3'","key='forma.volumetria.v4'")
a=a.replace("const saved=localStorage.getItem(key)","const saved=localStorage.getItem(key)||localStorage.getItem('forma.volumetria.v3')")
write('volumetria-v4-app.js',a)
f=read('volumetria-v3-features.js').replace('forma.options.v3','forma.options.v4').replace("version:'03'","version:'04.1'").replace('Forma-v03-estudo.json','Forma-v04-estudo.json').replace('Lote retangular plano, torres de mesma altura.','Lote plano retangular ou poligonal, torres de mesma altura.').replace('s.w*s.d','m.lotArea').replace("${o.state.w} × ${o.state.d} m", "${fmt(m.lotArea,0)} m² de lote")
f=f.replace('results:{height:', 'results:{lotArea:m.lotArea,height:')
write('volumetria-v4-features.js',f)
h=read('volumetria-v3-source.html').replace('Forma 03','Forma 04.1').replace('FORMA 03','FORMA 04.1').replace('class="version">03','class="version">04.1').replace('Nesta versão: lote retangular, solo plano e ruas na mesma cota.','Lote retangular ou poligonal, solo plano e ruas na mesma cota.').replace('Não inclui polígono irregular, terreno inclinado','Não inclui terreno inclinado')
h=h.replace('<div data-field="w">','<button id="open-lot-editor" style="width:100%;margin-bottom:12px">Desenhar / editar meu lote</button><p class="hint" id="polygon-summary"></p><div data-field="w">',1)
h=h.replace('Proposta</span><span>', 'Proposta</span><span><i class="dot" style="background:#8a9aa6"></i>Coroamento técnico</span><span>')
h=h.replace('<div data-field="n"></div>', '<details id="cut-explanation"><summary>Por que a proposta tem estes recortes?</summary><p>A camisa verde mostra os recuos do cenário. A proposta azul parte de retângulos de implantação: largura, profundidade e escala da base podem deixá-la menor que a camisa, especialmente em lotes inclinados ou irregulares. Esses cortes extras são escolhas do gerador, não exigências da lei.</p><p>Os pisos superiores também são contidos na projeção dos inferiores. O bloco cinza escuro é o coroamento técnico: sua redução para 64% da largura e profundidade da janela é uma convenção visual. Ajuste sua altura para zero para estudar sem ele.</p><p>Uma base a 100% ocupa a camisa disponível da base neste modelo, mas ainda precisa respeitar a taxa de ocupação aplicável. Na parte superior, H/10 usa a altura máxima do prédio e não a altura de cada andar.</p></details><div data-field="n"></div>',1)
h=h.replace('<div data-field="depth"></div>', '<div data-field="depth"></div>'+read('volumetria-v4-crown-ui.html'),1)
h=h.replace('sua redução para 64% da largura e profundidade da janela é uma convenção visual.', 'agora tem dimensões e posição ajustáveis, sem recorte do bloco.')
h=h.replace('<section id="panel-roads" role="tabpanel" aria-labelledby="tab-roads" hidden>','<section id="panel-roads" role="tabpanel" aria-labelledby="tab-roads" hidden><div id="polygon-roads-note" hidden><div class="summary-box">Neste lote, cada lado tem sua própria rua e regra de recuo. A largura da via não altera o recuo legal.</div><button id="edit-lot-roads">Editar ruas do polígono</button></div><div id="rectangle-roads">')
h=h.replace('<div id="road-error" class="notice" role="alert"></div></section>','<div id="road-error" class="notice" role="alert"></div></div></section>')
h=h.replace('</style>',read('volumetria-v4-editor.css')+'</style>')
h=h.replace('<script>/*__CORE__*/',read('volumetria-v4-editor.html')+'<script>/*__CORE__*/')
h=h.replace('<script>/*__RENDERER__*/','<script>/*__PC__*/</script><script>/*__EARCUT__*/</script><script>/*__POLYGON__*/</script><script>/*__CROWN__*/</script><script>/*__RENDERER__*/')
h=h.replace('</body>','<script>/*__EDITOR__*/</script><script>/*__CROWNUI__*/</script></body>')
for token,name in [('CORE','volumetria-v3-core.js'),('PC','polygon-clipping-0.15.7.js'),('EARCUT','earcut-2.2.4.js'),('POLYGON','volumetria-v4-polygon.js'),('RENDERER','volumetria-v4-renderer.js'),('APP','volumetria-v4-app.js'),('V3','volumetria-v4-features.js'),('EDITOR','volumetria-v4-editor.js'),('CROWN','volumetria-v4-crown.js'),('CROWNUI','volumetria-v4-crown-ui.js')]:
 h=h.replace('/*__'+token+'__*/',read(name))
h=h.replace('</head>', '<!-- Third-party libraries: polygon-clipping 0.15.7 and earcut 2.2.4.\n'+read('polygon-clipping-LICENSE.md')+'\n'+read('earcut-LICENSE.txt')+'\n--></head>')
write('Simulador-volumetrico-v04.html',h)
