(()=>{'use strict';
const $=id=>document.getElementById(id),V=Volumetry,key='forma.volumetria.v3';let s=V.clone(V.defaults),model,renderer,frame=0;
try{const saved=localStorage.getItem(key);if(saved)s=V.normalize(JSON.parse(saved));}catch(e){$('save-state').textContent='Sem armazenamento local';}
let lastCommitted=V.clone(s),history=[];
const format=(v,d=1)=>Number(v).toLocaleString('pt-BR',{maximumFractionDigits:d});const spec={floors:['Andares, contando o térreo',''],ground:['Altura do térreo','m'],storey:['Altura dos demais andares','m'],baseFloors:['Pavimentos na base',''],crown:['Coroamento técnico','m'],w:['Frente do lote','m'],d:['Profundidade do lote','m'],n:['Número de torres',''],fill:['Largura das torres','%'],depth:['Profundidade das torres','%'],baseCoverage:['Área ocupada pela base','%'],yaw:['Rotação','°'],pitch:['Inclinação','°'],zoom:['Zoom','%']};
for(const [id,[label,unit]]of Object.entries(spec)){const [min,max,step]=V.bounds[id],el=document.querySelector(`[data-field="${id}"]`);el.className='field';el.innerHTML=`<div class="field-head"><label for="range-${id}">${label}</label><span class="value-wrap"><input id="value-${id}" type="number" min="${min}" max="${max}" step="${step}" aria-label="${label}, valor numérico"><span>${unit}</span></span></div><input id="range-${id}" type="range" min="${min}" max="${max}" step="${step}" aria-label="${label}">`;
$('range-'+id).addEventListener('input',e=>{s[id]=+e.target.value;commit();});$('value-'+id).addEventListener('change',e=>{const v=e.target.valueAsNumber;if(Number.isFinite(v)){s[id]=v;commit();}else sync();});}
const names={front:'Frente',right:'Direita',back:'Fundos',left:'Esquerda'};for(const [side,name]of Object.entries(names)){const b=document.createElement('button');b.dataset.side=side;b.innerHTML=`${name}<small></small>`;b.onclick=()=>{s.roadSelected=side;syncRoad();persist();};$('road-picks').append(b);}
const tabs=[...document.querySelectorAll('[role=tab]')];function activate(tab){tabs.forEach(b=>{const selected=b===tab;b.setAttribute('aria-selected',selected);$(b.getAttribute('aria-controls')).hidden=!selected;});}
tabs.forEach((tab,i)=>{tab.onclick=()=>activate(tab);tab.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();let j=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length;activate(tabs[j]);tabs[j].focus();}};});
$('mode').onchange=e=>{s.mode=e.target.value;commit();};for(const k of ['grid','dimensions'])$(k).onchange=e=>{s[k]=e.target.checked;commit();};
$('theme').onclick=()=>{s.theme=s.theme==='light'?'dark':'light';commit();};$('road-enabled').onchange=e=>{s.roads[s.roadSelected].enabled=e.target.checked;commit();};$('road-aligned').onchange=e=>{s.roads[s.roadSelected].aligned=e.target.value==='yes';commit();};
for(const k of ['min','max'])$('road-'+k).onchange=e=>{const r=s.roads[s.roadSelected],v=e.target.valueAsNumber;if(!Number.isFinite(v)||v<6||v>60||(k==='min'?v>r.max:v<r.min)){syncRoad();$('road-error').textContent='Use 6 a 60 m, com mínimo menor ou igual ao máximo.';return;}r[k]=v;const old=r.width;r.width=Math.max(r.min,Math.min(r.max,r.width));commit();if(old!==r.width)$('road-error').textContent='A largura foi ajustada para permanecer no intervalo.';};
$('road-width').oninput=e=>{s.roads[s.roadSelected].width=+e.target.value;commit();};$('road-walk').oninput=e=>{s.roads[s.roadSelected].walk=+e.target.value;commit();};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const type=b.dataset.view;s.yaw=type==='front'?180:type==='plan'?180:145;s.pitch=type==='plan'?90:type==='front'?0:28;s.zoom=100;commit();});$('fit').onclick=()=>{s.zoom=100;commit();};
function syncRoad(){const r=s.roads[s.roadSelected];document.querySelectorAll('[data-side]').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.side===s.roadSelected);b.querySelector('small').textContent=s.roads[b.dataset.side].enabled?'Exibida':'Oculta';});$('road-enabled').checked=r.enabled;$('road-min').value=r.min;$('road-max').value=r.max;const input=$('road-width');input.min=r.min;input.max=r.max;input.value=r.width;$('road-value').textContent=format(r.width)+' m';$('road-walk').max=Math.min(5,(r.width-3)/2);$('road-walk').value=r.walk;$('walk-value').textContent=format(r.walk)+' m';$('road-aligned').value=r.aligned?'yes':'no';$('road-equation').textContent=`${format(r.walk)} + ${format(r.width-r.walk*2)} + ${format(r.walk)} m`;$('road-error').textContent='';}
function sync(){document.documentElement.dataset.theme=s.theme;for(const id of Object.keys(spec)){$('range-'+id).value=s[id];$('value-'+id).value=s[id];}$('mode').value=s.mode;$('grid').checked=s.grid;$('dimensions').checked=s.dimensions;$('theme').textContent=s.theme==='light'?'Escuro':'Claro';$('theme').setAttribute('aria-label',s.theme==='light'?'Ativar tema escuro':'Ativar tema claro');syncRoad();document.querySelectorAll('[data-view]').forEach(b=>{const match=b.dataset.view==='plan'?s.pitch===90:b.dataset.view==='front'?s.yaw===180&&s.pitch===0:s.yaw===145&&s.pitch===28;b.setAttribute('aria-pressed',match);});
$('metric-height').textContent=format(model.H)+' m';$('metric-floors').textContent=`${s.floors} pavimentos · + ${format(s.crown)} m técnicos`;$('metric-setback').textContent=format(model.a,2)+' m';$('metric-gap').textContent=s.n>1?'Entre torres ≥ '+format(model.gap,2)+' m':'Uma torre';$('metric-occupation').textContent=model.valid?format(model.occupation)+'%':'—';$('metric-area').textContent=model.valid?format(model.projection,0)+' m² de projeção':'Geometria inviável';$('height-equation').textContent=`${format(s.ground)} + ${s.floors-1} × ${format(s.storey)} = ${format(model.H)} m`;$('base-hint').textContent=`Base efetiva: ${model.baseFloors} pavimentos / ${format(model.baseHeight)} m. Coroamento sem uso habitável; não entra em H.`;
const status=$('status');status.className='status'+(!model.valid?' error':model.warnings.length?' warning':'');status.textContent=model.warnings.length?model.warnings.join(' '):model.crossing>0?`O pavimento ${model.crossing} cruza 15 m e recebe integralmente o recuo superior. Índices específicos da zona não verificados.`:'Geometria ajustada aos recuos modelados. Altura máxima e taxa de ocupação da zona ainda não verificadas.';
$('scene').setAttribute('aria-label',`${s.n} torres de ${s.floors} pavimentos, altura habitável ${format(model.H)} metros. ${status.textContent}`);
const data=[['H · altura habitável',format(model.H)+' m · coroamento excluído'],['G · gabarito',s.floors+' pavimentos, incluindo térreo'],['Afastamento lateral / fundos',format(model.a,2)+' m no trecho habitável superior'],['Distância mínima entre torres',s.n>1?format(model.gap,2)+' m':'Não se aplica a uma torre'],['Base efetiva',model.baseFloors+' pavimentos · '+format(model.baseHeight)+' m'],['Área bruta de pisos',format(model.area,0)+' m² · sem descontos legais'],['Volume habitável',format(model.volume,0)+' m³ · coroamento excluído']];$('rules-live').replaceChildren(...data.map(([label,val])=>{const div=document.createElement('div');div.className='rule';const a=document.createElement('strong'),b=document.createElement('span');a.textContent=label;b.textContent=val;div.append(a,b);return div;}));}
function persist(){try{localStorage.setItem(key,JSON.stringify(s));$('save-state').textContent='Salvo neste navegador';}catch(e){$('save-state').textContent='Alterações nesta sessão';}}
function requestDraw(){if(frame)return;frame=requestAnimationFrame(()=>{frame=0;if(renderer)renderer.draw(model);});}
function commit(){if(JSON.stringify(s)!==JSON.stringify(lastCommitted)){history.push(V.clone(lastCommitted));if(history.length>40)history.shift();}s=V.normalize(s);lastCommitted=V.clone(s);model=V.calculate(s);sync();requestDraw();persist();window.dispatchEvent(new Event('forma:update'));}
model=V.calculate(s);sync();try{renderer=createVolumetryRenderer($('scene'),$('labels'));requestDraw();}catch(e){$('status').className='status error';$('status').textContent=e.message;$('export').disabled=true;}
new ResizeObserver(requestDraw).observe($('scene'));window.addEventListener('resize',requestDraw);
const pointers=new Map();let pinch=null;const scene=$('scene');scene.onpointerdown=e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});scene.setPointerCapture(e.pointerId);if(pointers.size===2){const [a,b]=[...pointers.values()];pinch=Math.hypot(a.x-b.x,a.y-b.y);}};
scene.onpointermove=e=>{const old=pointers.get(e.pointerId);if(!old)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const[a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinch>0)s.zoom=Math.max(50,Math.min(180,s.zoom*d/pinch));pinch=d;}else{s.yaw=((s.yaw+(e.clientX-old.x)*.45+540)%360)-180;s.pitch=Math.max(0,Math.min(90,s.pitch+(e.clientY-old.y)*.3));}s=V.normalize(s);model={...model,p:s};sync();requestDraw();};
function end(e){pointers.delete(e.pointerId);pinch=null;commit();}scene.onpointerup=end;scene.onpointercancel=end;scene.onlostpointercapture=e=>{pointers.delete(e.pointerId);pinch=null;};scene.addEventListener('wheel',e=>{e.preventDefault();s.zoom-=e.deltaY*.06;commit();},{passive:false});
scene.addEventListener('webglcontextlost',e=>{e.preventDefault();$('status').className='status error';$('status').textContent='Visualização 3D interrompida. Recarregue a página; seus parâmetros estão salvos.';$('export').disabled=true;});
$('export').onclick=()=>{if(!renderer)return;const a=document.createElement('a');a.href=renderer.exportImage();a.download='Forma-estudo-volumetrico.png';a.click();};
window.forma={getState:()=>V.clone(s),getModel:()=>model,setState:input=>{s=V.normalize({...s,...input});commit();},get canUndo(){return history.length>0;},undo(){if(!history.length)return;s=history.pop();lastCommitted=V.clone(s);model=V.calculate(s);sync();requestDraw();persist();window.dispatchEvent(new Event('forma:update'));},get renderer(){return renderer;}};
})();

